## Runscribe: Comparison of Data on Treadmill & Outdoors

### data cleaning code - outdoor running
* note: the calibration run was used for all subjects

In [1]:
# import dependencies
import pandas as pd

#### 20501, RS #12, competitive adult

In [2]:
# read in csv's
rs_012_20181001_L_df = pd.read_csv("data/outdoor/012_L_20181001.csv")
rs_012_20181001_R_df = pd.read_csv("data/outdoor/012_R_20181001.csv")
rs_012_20181001_L_2_df = pd.read_csv("data/outdoor/012_L_20181001_extra.csv")
rs_012_20181001_R_2_df = pd.read_csv("data/outdoor/012_R_20181001_extra.csv")
rs_012_20181002_L_df = pd.read_csv("data/outdoor/012_L_20181002.csv")
rs_012_20181003_L_df = pd.read_csv("data/outdoor/012_L_20181003.csv")
rs_012_20181003_R_df = pd.read_csv("data/outdoor/012_R_20181003.csv")
rs_012_20181004_L_df = pd.read_csv("data/outdoor/012_L_20181004.csv")
rs_012_20181004_R_df = pd.read_csv("data/outdoor/012_R_20181004.csv")

# add laterality and date tags
rs_012_20181001_L_df['laterality'] = 'left'
rs_012_20181001_L_df['date'] = '2018-10-01'

rs_012_20181001_R_df['laterality'] = 'right'
rs_012_20181001_R_df['date'] = '2018-10-01'

rs_012_20181001_L_2_df['laterality'] = 'left'
rs_012_20181001_L_2_df['date'] = '2018-10-01'

rs_012_20181001_R_df['laterality'] = 'right'
rs_012_20181001_R_df['date'] = '2018-10-01'

rs_012_20181002_L_df['laterality'] = 'left'
rs_012_20181002_L_df['date'] = '2018-10-02'

rs_012_20181003_L_df['laterality'] = 'left'
rs_012_20181003_L_df['date'] = '2018-10-03'

rs_012_20181003_R_df['laterality'] = 'right'
rs_012_20181003_R_df['date'] = '2018-10-03'

rs_012_20181004_L_df['laterality'] = 'left'
rs_012_20181004_L_df['date'] = '2018-10-04'

rs_012_20181004_R_df['laterality'] = 'right'
rs_012_20181004_R_df['date'] = '2018-10-04'

rs_012_df = pd.concat([rs_012_20181001_L_df, rs_012_20181001_R_df,
                       rs_012_20181001_L_2_df, rs_012_20181001_R_2_df, 
                       rs_012_20181002_L_df,
                       rs_012_20181003_L_df, rs_012_20181003_R_df,
                       rs_012_20181004_L_df, rs_012_20181004_R_df], sort = True)

# add other metrics to dataframe
rs_012_df['injury_status'] = 'healthy'
rs_012_df['subject_id'] = '012'

#### H001, RS #004, healthy

In [3]:
# read in csv's
rs_004_20180330_L_df = pd.read_csv("data/outdoor/004_L_20180330.csv")
rs_004_20180330_R_df = pd.read_csv("data/outdoor/004_R_20180330.csv")
rs_004_20180405_L_df = pd.read_csv("data/outdoor/004_L_20180405.csv")
rs_004_20180405_R_df = pd.read_csv("data/outdoor/004_R_20180405.csv")

# add laterality and date tags
rs_004_20180330_L_df['laterality'] = 'left'
rs_004_20180330_L_df['date'] = '2018-03-30'

rs_004_20180330_R_df['laterality'] = 'right'
rs_004_20180330_R_df['date'] = '2018-03-30'

rs_004_20180405_L_df['laterality'] = 'left'
rs_004_20180405_L_df['date'] = '2018-04-05'

rs_004_20180405_R_df['laterality'] = 'right'
rs_004_20180405_R_df['date'] = '2018-04-05'

rs_004_df = pd.concat([rs_004_20180330_R_df, rs_004_20180330_L_df,
                       rs_004_20180405_R_df, rs_004_20180405_R_df])

# add other metrics to dataframe
rs_004_df['injury_status'] = 'healthy'
rs_004_df['subject_id'] = '004'

In [4]:
# read in addition outdoor runs for RFC

#### 20501, RS #16, ERLLP

In [5]:
# read in csv's
rs_016_20180412_L_df = pd.read_csv("data/outdoor/016_L_20180412.csv")
rs_016_20180412_R_df = pd.read_csv("data/outdoor/016_R_20180412.csv")
rs_016_20180416_L_df = pd.read_csv("data/outdoor/016_L_20180416.csv")
rs_016_20180416_R_df = pd.read_csv("data/outdoor/016_R_20180416.csv")

# add laterality and date tags
rs_016_20180412_L_df['laterality'] = 'left'
rs_016_20180412_L_df['date'] = '2018-04-12'

rs_016_20180412_R_df['laterality'] = 'right'
rs_016_20180412_R_df['date'] = '2018-04-12'

rs_016_20180416_L_df['laterality'] = 'left'
rs_016_20180416_L_df['date'] = '2018-04-16'

rs_016_20180416_R_df['laterality'] = 'right'
rs_016_20180416_R_df['date'] = '2018-04-16'

rs_016_df = pd.concat([rs_016_20180412_L_df, rs_016_20180412_R_df,
                       rs_016_20180416_L_df, rs_016_20180416_R_df])

# add other metrics to dataframe
rs_016_df['injury_status'] = 'erllp'
rs_016_df['subject_id'] = '016'

#### H011, RS #023, healthy

In [6]:
# read in csv's
rs_023_20180424_L_df = pd.read_csv("data/outdoor/023_L_20180424.csv")
rs_023_20180424_R_df = pd.read_csv("data/outdoor/023_R_20180424.csv")
rs_023_20180426_L_df = pd.read_csv("data/outdoor/023_L_20180426.csv")
rs_023_20180426_R_df = pd.read_csv("data/outdoor/023_R_20180426.csv")
rs_023_20180430_L_df = pd.read_csv("data/outdoor/023_L_20180430.csv")
rs_023_20180430_R_df = pd.read_csv("data/outdoor/023_R_20180430.csv")

# add laterality and date tags
rs_023_20180424_L_df['laterality'] = 'left'
rs_023_20180424_L_df['date'] = '2018-04-24'
rs_023_20180424_L_df.head()

# add laterality and date tags
rs_023_20180424_R_df['laterality'] = 'right'
rs_023_20180424_R_df['date'] = '2018-04-24'
rs_023_20180424_R_df.head()

rs_023_20180426_L_df['laterality'] = 'left'
rs_023_20180426_L_df['date'] = '2018-04-26'

rs_023_20180426_R_df['laterality'] = 'right'
rs_023_20180426_R_df['date'] = '2018-04-26'

rs_023_20180430_L_df['laterality'] = 'left'
rs_023_20180430_L_df['date'] = '2018-04-30'

rs_023_20180430_R_df['laterality'] = 'right'
rs_023_20180430_R_df['date'] = '2018-04-30'

rs_023_df = pd.concat([rs_023_20180424_L_df, rs_023_20180424_R_df,
                       rs_023_20180426_L_df, rs_023_20180426_R_df,
                       rs_023_20180430_L_df, rs_023_20180430_R_df])

# add other metrics to dataframe
rs_023_df['injury_status'] = 'healthy'
rs_023_df['subject_id'] = '023'

#### 20501, RS027, ERLLP

In [7]:
# read in csv's
rs_027_20180526_L_df = pd.read_csv("data/outdoor/027_L_20180526.csv")
rs_027_20180526_R_df = pd.read_csv("data/outdoor/027_R_20180526.csv")
rs_027_20180528_L_df = pd.read_csv("data/outdoor/027_L_20180528.csv")
rs_027_20180528_R_df = pd.read_csv("data/outdoor/027_R_20180528.csv")
rs_027_20180528_L_df = pd.read_csv("data/outdoor/027_L_20180528.csv")
rs_027_20180528_R_df = pd.read_csv("data/outdoor/027_R_20180528.csv")
rs_027_20180531_L_df = pd.read_csv("data/outdoor/027_L_20180531.csv")
rs_027_20180531_R_df = pd.read_csv("data/outdoor/027_R_20180531.csv")
rs_027_20180604_L_df = pd.read_csv("data/outdoor/027_L_20180604.csv")
rs_027_20180604_R_df = pd.read_csv("data/outdoor/027_R_20180604.csv")

# add laterality and date tags
rs_027_20180526_L_df['laterality'] = 'left'
rs_027_20180526_L_df['date'] = '2018-05-26'
rs_027_20180526_L_df.head()

rs_027_20180526_R_df['laterality'] = 'right'
rs_027_20180526_R_df['date'] = '2018-05-26'
rs_027_20180526_R_df.head()

rs_027_20180528_L_df['laterality'] = 'left'
rs_027_20180528_L_df['date'] = '2018-05-28'

rs_027_20180528_R_df['laterality'] = 'right'
rs_027_20180528_R_df['date'] = '2018-05-28'

rs_027_20180531_L_df['laterality'] = 'left'
rs_027_20180531_L_df['date'] = '2018-05-31'

rs_027_20180531_R_df['laterality'] = 'right'
rs_027_20180531_R_df['date'] = '2018-05-31'

rs_027_20180604_L_df['laterality'] = 'left'
rs_027_20180604_L_df['date'] = '2018-06-04'

rs_027_20180604_R_df['laterality'] = 'right'
rs_027_20180604_R_df['date'] = '2018-06-04'

# merge dataframes
rs_027_df = pd.concat([rs_027_20180526_L_df, rs_027_20180526_R_df,
                       rs_027_20180528_L_df, rs_027_20180528_R_df,
                       rs_027_20180531_L_df, rs_027_20180531_R_df,
                       rs_027_20180604_L_df, rs_027_20180604_R_df])

# add other metrics to dataframe
rs_027_df['injury_status'] = 'erllp'
rs_027_df['subject_id'] = '027'

#### Merge all dataframes together

In [11]:
outdoor_df = pd.concat([rs_004_df, rs_012_df, 
                        rs_016_df, rs_023_df,
                        rs_027_df], sort = True)

outdoor_df['medium'] = 'outdoor'

In [12]:
# Export to csv
outdoor_df.to_csv("output/outdoor_df.csv", index = False)

In [13]:
outdoor_df.groupby('subject_id').max()

,braking_gs,contact_ratio,contact_time,cycle_time,debug_1,debug_2,flight_ratio,flight_time,footstrike_type,footstrike_type_new,...,stance_excursion_mp_to,step,step_length,step_rate,stride_angle,stride_length,stride_pace,timestamp,walking,medium
subject_id,,,,,,,,,,,,,,,,,,,,,
004,15.9922,855.6522,1070,1340,152.2930,23.9844,39.9441,143,16,10.0,...,108.4709,3818,1.7685,237.1542,60.1564,3.5370,5.0892,2731291,NaN,outdoor
012,15.9961,669.3750,1071,1380,141.1680,32.7461,94.8529,307,16,10.0,...,224.5757,3894,2.9448,252.6316,53.9331,5.8896,9.0215,3014510,NaN,outdoor
016,15.9883,1030.0000,1005,1356,120.0000,35.5859,45.3441,123,16,10.0,...,108.1387,2839,2.5951,258.0645,42.6289,5.1902,6.8678,3090075,NaN,outdoor
023,15.9922,942.2535,759,1255,146.0820,29.6875,71.8157,265,16,10.0,...,329.2694,2283,2.1178,231.2139,36.7285,4.2356,5.7627,1682077,NaN,outdoor
027,15.9961,276.3158,780,1153,130.3047,21.5859,38.3562,140,16,10.0,...,106.8319,3317,1.7473,193.8611,18.7303,3.4945,4.9288,2385246,NaN,outdoor